data:
#    train: './data/french_reinflected_train.conllu'
#    checkpoint: './data/language_model_reinflected.pt'
#    vocab: './data/vocab.pk'
    train: './data/english-train.conllu'
    dev: './data/english-dev.conllu'
    checkpoint: './data/language_model_eng.pt'

model:
    embedding_dim: 200
    hidden_size: 512
    num_layers: 2

training:
    num_epochs: 25
    batch_size: 8
